python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\3.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\4.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\5.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\6.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\7.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\8.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\9.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\10.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\11.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\12.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\13.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\14.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\15.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\16.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\17.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\18.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\19.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\20.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\21.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\22.json
python generateCSV.py D:\Documents\workspace\pbscires\generatecsvs\23.json