python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb05.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb05.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb06.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb06.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb07.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb07.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb08.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb08.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb09.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb09.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb10.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb10.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb11.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb11.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb12.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb12.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb13.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb13.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb14.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb14.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb15.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb15.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb16.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb16.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb17.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb17.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb18.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb18.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb19.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb19.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb20.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb20.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb21.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb21.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb22.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb22.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb23.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb23.Xy_test.csv
python useClassifier.py D:\Documents\ReadyForTensorFlow\LineLength\chb24.Xy_train.csv D:\Documents\ReadyForTensorFlow\LineLength\chb24.Xy_test.csv