#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
This script contains methods to evaluate the results generated by
the classifier models in Test and Fit sub directories.
"""

def getRecall():
    # ToDo:
    # Recall: What fraction of all positive instances doe sthe classifier 
    #         correctly identify as positive?
    # Recall = True Positive Rate (TPR) = TP / (TP + FN)
    return (0)

def getSpecificity():
    # ToDo:
    # Specificity or False positive rate (FPR): what fraction of all 
    #      negative instances does the classifier identify as positive
    # Specificity = FPR = FP / (TN + FP)
    return (0)

def getAccuracy():
    # ToDo
    # Accuracy: for what fraction of all instances is the classifier's prediction
    # correct (for either positive or negative class)
    # Accuracy = (TP + TN) / (TP + TN + FP + FN)
    return (0)

def getPrecision():
    # ToDo:
    # Precision : What fraction of Positive Predictions are correct?
    # Precision = TP / (TP + FP)
    return (0)
